controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# controllers_api:
#     resource: 
#         path: '../src/Api/'
#         namespace: App\Api
#     type: attribute

api_login_check:
    path: /api/login_check